# Generated by Django 3.2.8 on 2021-12-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20211209_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
