# Generated by Django 3.2.8 on 2021-12-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
