# Generated by Django 3.2.8 on 2021-12-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_delete_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pic',
            field=models.ForeignKey(default=73, on_delete=django.db.models.deletion.CASCADE, to='network.image'),
        ),
    ]
