# Generated by Django 3.2.8 on 2021-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_upvotes',
            field=models.ManyToManyField(blank=True, to='network.Post'),
        ),
    ]
