# Generated by Django 3.2.8 on 2021-12-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='user_upvotes',
            field=models.ManyToManyField(blank=True, related_name='user_upvotes', to='network.Post'),
        ),
    ]
